### ISSUE TITLE
nsd export height=2 panics

### ISSUE THREAD

**Issue by cbarraford** [cosmos/sdk-tutorials#327]
Noticed in my app that I'm developing that when i try to export a certain block height i get the following panic. To check if it was something in my code or not, i spun up the nameservice tutorial and was able to recreate the problem. Not sure if its a bug in the tutorial, or a bug in cosmos 0.38

```
$ nsd export --height 2
panic: app.baseKey expected to be nil; duplicate init?

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).initFromMainStore(0xc000113680, 0xc0005193c0, 0x0, 0x0)
    /Users/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.4/baseapp/baseapp.go:314 +0x2a0
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).LoadVersion(0xc000113680, 0x2, 0xc0005193c0, 0x4, 0xc0000c7cf8)
    /Users/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.4/baseapp/baseapp.go:292 +0x80
github.com/cosmos/sdk-tutorials/nameservice.(*nameServiceApp).LoadHeight(...)
    /Users/user/go/src/github.com/cosmos/sdk-tutorials/nameservice/app.go:301
main.exportAppStateAndTMValidators(0x520a880, 0xc000f2a820, 0x521ed80, 0xc0000da140, 0x0, 0x0, 0x2, 0xc000f2a800, 0x5afb2a8, 0x0, ...)
    /Users/user/go/src/github.com/cosmos/sdk-tutorials/nameservice/cmd/nsd/main.go:81 +0xe5
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc000e59600, 0xc000e27260, 0x0, 0x2, 0x0, 0x0)
    /Users/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.4/server/export.go:65 +0x53d
github.com/spf13/cobra.(*Command).execute(0xc000e59600, 0xc000e27220, 0x2, 0x2, 0xc000e59600, 0xc000e27220)
    /Users/user/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e42000, 0x2, 0xc000e27180, 0x4ebff1c)
    /Users/user/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
    /Users/user/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000e42000, 0x5024430, 0x2, 0xc000e290e0)
    /Users/user/go/pkg/mod/github.com/tendermint/tendermint@v0.33.3/libs/cli/setup.go:89 +0x3c
main.main()
    /Users/user/go/src/github.com/cosmos/sdk-tutorials/nameservice/cmd/nsd/main.go:65 +0x784
```

**Comment by marbar3778** [comment]
Are you able to recreate this issue with gaia?

**Comment by cbarraford** [comment]
no, i personally don't use gaia, so im not setup to try. I'm building my own chain and am able to reproduce this issue within my own app. Another person on the discord said they can reproduce this problem on ethermint as well.

**Comment by xavierlepretre** [comment]
This refers to obsolete content.
